from src.core.schemas.events import *

class ActionEventHandlersMixin:
    """Интерфейс для хэндлеров action ивентов"""
    def on_key_down(self, obj: KeyDownModel) -> None: ...
    def on_key_up(self, obj: KeyUpModel) -> None: ...
    def on_will_appear(self, obj: WillAppearModel) -> None: ...
    def on_will_disappear(self, obj: WillDisappearModel) -> None: ...
    def on_did_receive_settings(self, obj: DidReceiveSettingsModel) -> None: ...
    def on_property_inspector_did_appear(self, obj: PropertyInspectorDidAppearModel) -> None: ...
    def on_send_to_plugin(self, obj: SendToPluginModel) -> None: ...
    def on_title_parameters_did_change(self, obj: TitleParametersDidChangeModel) -> None: ...

class PluginEventHandlersMixin:
    """Интерфейс для хэндлеров plugin ивентов"""
    def on_did_receive_global_settings(self, obj: DidReceiveGlobalSettingsModel) -> None: ...
    def on_system_did_wake_up(self, obj: SystemDidWakeUpModel) -> None: ...
    def on_application_did_launch(self, obj: ApplicationDidLaunchModel) -> None: ...
    def on_application_did_terminate(self, obj: ApplicationDidTerminateModel) -> None: ...
    def on_send_to_plugin(self, obj: SendToPluginModel) -> None: ...
