from src.actions.playpause import PlayPause
from src.actions.next import NextTrack
from src.actions.prev import PrevTrack
from src.actions.like import Like
from src.actions.dislike import Dislike
from src.actions.info import Info
from src.actions.progress import Progress
from src.actions.volumeup import VolumeUp
from src.actions.volumedown import VolumeDown
from src.actions.volume_display import VolumeDisplay
from src.actions.mute import Mute